DROP DATABASE IF EXISTS cookies_db;
CREATE DATABASE cookies_db;

USE cookies_db;
CREATE TABLE cookies(
  id INT(10) AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  devoured BOOL NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
);